---
- name: Download oc CLI
  get_url:
    url: https://github.com/openshift/okd/releases/download/4.6.0-0.okd-2021-01-23-132511/openshift-client-linux-4.6.0-0.okd-2021-01-23-132511.tar.gz
    dest: /tmp/openshift-client-linux.tar.gz

- name: Extract oc CLI
  unarchive:
    src: /tmp/openshift-client-linux.tar.gz
    dest: /usr/local/bin
    remote_src: yes
  become: yes

- name: Ensure oc CLI is executable
  file:
    path: /usr/local/bin/oc
    mode: '0755'
  become: yes

