apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
spec:
  replicas: 3  # Specify the number of replicas if you want more than one pod
  selector:
    matchLabels:
      app: java-deployment
  template:
    metadata:
      labels:
        app: java-deployment
    spec:
      containers:
      - name: java-app
        image: osayman74/java-app:latest
        ports:
        - containerPort: 8082
        # resources:  # Optional: Add resource requests and limits
        #   requests:
        #     memory: "256Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "512Mi"
        #     cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: java-deployment
spec:
  selector:
    app: java-deployment
  ports:
  - port: 8082
    targetPort: 8082
  type: ClusterIP  # Optional: Specify the type of service (ClusterIP, NodePort, LoadBalancer)

