apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/osamaayman/IVOLVE-OJT/OpenShift/lab-3  # Update this with the path on your host machine
