---
- name: MySQL Server Configuration
  hosts: my_hosts
  become: true
  vars_files:
    - vars/mysql_credentials.yml  # Ansible Vault encrypted file containing MySQL credentials
  
  tasks:
    - name: Install MySQL Server
      apt:
        name: 
        - mysql-server
        - python3-mysqldb
        state: present
  
    - name: Ensure MySQL Service is Running
      service:
        name: mysql.service
        state: started
      notify: restart mysql

    - name: Create `/root/.my.cnf` with root password credentials
      template:
        src:  my.cnf.j2
        dest: /root/.my.cnf
        owner: root
        mode: 0600

    - name: Ensure mysql root password is updated for all root accounts
      mysql_user:
        check_implicit_admin: yes
        login_user: root
        login_password: "{{ mysql_root_password }}"
        user: root
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    # - name: Create a new MySQL user without grant option
    #   mysql_user:
    #     name: "{{mysql_username}}"
    #     password: "{{mysql_password}}"
    #     state: present
    #     login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create a new database
      mysql_db:
        name: ivolve-test
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Add sample data to database
      copy:
        src: ./dump.sql
        dest: /tmp/dump.sql

    - name: Insert sample data into database
      mysql_db:
        name: ivolve-test
        state: import
        target: /tmp/dump.sql
        login_user: root
        login_password: "{{ mysql_root_password }}"
